----- DIFF | diff file1 file2---------------------------------------------------------------
< = removed  
> = added 

5c5,6 = on line 5, c= Changed 
11a13,15 = a = added 13-15 new lines

----- SHOW MORE details | diff -u file1 file2---------------------------------------------------------------

----- SHOW MORE details and create a file showing this | diff -u file1OG.py file2fixed.py > file3.diff---------------------------------------------------------------

----- PATCH - takes a file generated by diff and applies changes to original file  ---------------------------------------------------------------
        patch ogfile < difffile

----- GIT SETUP / LOGIN  ---------------------------------------------------------------
git config --global user.email "me@example.com"
git config --global user.name "My name"

----- CREATE NEW REPO  ---------------------------------------------------------------
mkdir <dirName>
cd <dirName>
git init

----- TRACK USING GIT (STAGING)  ---------------------------------------------------------------
git add file.py
git status

----- GET CURRENT WORKING TREE & PENDING CHANGES   ---------------------------------------------------------------
git status

----- COMMIT w/ EDITOR  ---------------------------------------------------------------
git commit (opens text editor)

(commit message will be needed, add notes about the commit)

----- COMMIT WITH COMMENT W/O opening editor |  ---------------------------------------------------------------
git commit -m '<MESSAGE>'

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------