----- DIFF | diff file1 file2---------------------------------------------------------------
< = removed  
> = added 

5c5,6 = on line 5, c= Changed 
11a13,15 = a = added 13-15 new lines

----- SHOW MORE details | diff -u file1 file2---------------------------------------------------------------
----- SHOW MORE details and create a file showing this | diff -u file1OG.py file2fixed.py > file3.diff---------------------------------------------------------------
----- PATCH - takes a file generated by diff and applies changes to original file  ---------------------------------------------------------------
        patch ogfile < difffile

----- Tell git who we are  ---------------------------------------------------------------
git config --global user.email "me@example.com"
git config --global user.name "My name"
----- create new dir in new Repo then create git in new repo  ---------------------------------------------------------------
mkdir checks
cd checks
git init
----- track something using git  ---------------------------------------------------------------
git add file.py
git status
-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------

-----   ---------------------------------------------------------------